# Generated by Django 2.2.13 on 2020-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Vue.js', 'Vue.js')], default='Python', max_length=6)),
                ('aktif', models.BooleanField(default=True)),
                ('tgl_masuk', models.DateTimeField(auto_now_add=True)),
                ('poin', models.IntegerField()),
            ],
        ),
    ]
